spring:
  ai:
    mcp:
      server:
        name: author-tool-server
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: /mcp/message
        stdio: false
        enabled: true

server:
  port: 8088

logging:
  level:
    org:
      springframework:
        ai: DEBUG